base $10
global_module_index:
!GLOBAL_MODULE_STARTUP = $00
!GLOBAL_MODULE_GAME_SELECT = $01
!GLOBAL_MODULE_COPY_PLAYER = $02
!GLOBAL_MODULE_ERASE_PLAYER = $03
!GLOBAL_MODULE_NAME_PLAYER = $04
!GLOBAL_MODULE_LOADING_GAME = $05
!GLOBAL_MODULE_PRE_DUNGEON = $06
!GLOBAL_MODULE_DUNGEON = $07
!GLOBAL_MODULE_PRE_OVERWORLD = $08
!GLOBAL_MODULE_OVERWORLD = $09
!GLOBAL_MODULE_PRE_OVERWORLD_SPECIAL = $0A
!GLOBAL_MODULE_OVERWORLD_SPECIAL = $0B
!GLOBAL_MODULE_UNUSED = $0C
!GLOBAL_MODULE_BLANK_SCREEN = $0D
!GLOBAL_MODULE_TEXTBOX_ITEMS_OR_MAP = $0E
!GLOBAL_MODULE_CLOSING_SPOTLIGHT = $0F
!GLOBAL_MODULE_OPENING_SPOTLIGHT = $10
!GLOBAL_MODULE_FALL_INTO_OVERWORLD_HOLE = $11
!GLOBAL_MODULE_DEATH = $12
!GLOBAL_MODULE_BOSS_VICTORY = $13
!GLOBAL_MODULE_HISTORY = $14
!GLOBAL_MODULE_MAGIC_MIRROR = $15
!GLOBAL_MODULE_REFILL_STATS_AFTER_BOSS = $16
!GLOBAL_MODULE_RESTARTING_AFTER_SAVE_AND_QUIT = $17
!GLOBAL_MODULE_GANON_RISES_FROM_AGAHNIM_BODY = $18
!GLOBAL_MODULE_TRIFORCE_ROOM = $19
!GLOBAL_MODULE_END_SEQUENCE = $1A
!GLOBAL_MODULE_SELECT_STARTING_LOCATION = $1B

base $11
global_submodule_index:
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;submodules of GLOBAL_MODULE_TEXTBOX_ITEMS_OR_MAP:
!GLOBAL_MODULE_TEXTBOX_ITEMS_OR_MAP_SUBMODULE_ABORT = $00
!GLOBAL_MODULE_TEXTBOX_ITEMS_OR_MAP_SUBMODULE_ITEM_MENU = $01
!GLOBAL_MODULE_TEXTBOX_ITEMS_OR_MAP_SUBMODULE_DIALOGUE = $02
!GLOBAL_MODULE_TEXTBOX_ITEMS_OR_MAP_SUBMODULE_DUNGEON_MAP = $03
!GLOBAL_MODULE_TEXTBOX_ITEMS_OR_MAP_SUBMODULE_LIFE_FILL_UP = $04
!GLOBAL_MODULE_TEXTBOX_ITEMS_OR_MAP_SUBMODULE_DESERT_PALACE_PRAYER = $05
!GLOBAL_MODULE_TEXTBOX_ITEMS_OR_MAP_SUBMODULE_UNUSED = $06
!GLOBAL_MODULE_TEXTBOX_ITEMS_OR_MAP_SUBMODULE_OVERWORLD_MAP = $07
!GLOBAL_MODULE_TEXTBOX_ITEMS_OR_MAP_SUBMODULE_MAGIC_FILL_UP = $08
!GLOBAL_MODULE_TEXTBOX_ITEMS_OR_MAP_SUBMODULE_LIFE_AND_MAGIC_FILL_UP = $09
!GLOBAL_MODULE_TEXTBOX_ITEMS_OR_MAP_SUBMODULE_DUCK = $0A
!GLOBAL_MODULE_TEXTBOX_ITEMS_OR_MAP_SUBMODULE_CONTINUE_OR_QUIT_MENU = $0B
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

base $1A
frame_counter:

base $2F
link_facing_direction:
!LINK_FACING_DIRECTION_UP = $00
!LINK_FACING_DIRECTION_DOWN = $02
!LINK_FACING_DIRECTION_LEFT = $04
!LINK_FACING_DIRECTION_RIGHT = $06

base $46
link_ignore_controls_timer:

base $4D
link_motility_type:
!LINK_MOTILITY_TYPE_NORMAL = $00
!LINK_MOTILITY_TYPE_RECOIL = $01
!LINK_MOTILITY_TYPE_WATER_TRANSITION = $02
!LINK_MOTILITY_TYPE_SWIMMING = $04

base $5D
link_present_action:
!LINK_PRESENT_ACTION_NORMAL = $00
!LINK_PRESENT_ACTION_FALLING_INTO_A_HOLE = $01
!LINK_PRESENT_ACTION_BONK_OR_HURT = $02
!LINK_PRESENT_ACTION_BEGINNING_SPIN_ATTACK = $03
!LINK_PRESENT_ACTION_SWIMMING = $04
!LINK_PRESENT_ACTION_ON_SOMARIA_PLATFORM = $05
!LINK_PRESENT_ACTION_RECOIL_ALTERNATE = $06
!LINK_PRESENT_ACTION_ZAPPED_BY_AGHANIM = $07
!LINK_PRESENT_ACTION_USING_ETHER = $08
!LINK_PRESENT_ACTION_USING_BOMBOS = $09
!LINK_PRESENT_ACTION_USING_QUAKE = $0A
!LINK_PRESENT_ACTION_FALLING_OFF_A_LEDGE = $11
!LINK_PRESENT_ACTION_TURNING_OUT_OF_A_DASH = $12
!LINK_PRESENT_ACTION_HOOKSHOT = $13
!LINK_PRESENT_ACTION_MAGIC_MIRROR = $14
!LINK_PRESENT_ACTION_HOLDING_UP_AN_ITEM = $15
!LINK_PRESENT_ACTION_ASLEEP_IN_BED = $16
!LINK_PRESENT_ACTION_PERMA_BUNNY_FORM = $17
!LINK_PRESENT_ACTION_STUCK_UNDER_A_ROCK = $18
!LINK_PRESENT_ACTION_RECEIVING_ETHER = $19
!LINK_PRESENT_ACTION_RECEIVING_BOMBOS = $1A
!LINK_PRESENT_ACTION_OPENING_DESERT_PALACE = $1B
!LINK_PRESENT_ACTION_BUNNY_BEAM_FORM = $1C
!LINK_PRESENT_ACTION_TREE_PULL_RECOIL = $1D
!LINK_PRESENT_ACTION_PERFORMING_SPIN_ATTACK = $1E

base $5E
link_movement_speed_setting:
!LINK_MOVEMENT_SPEED_SETTING_NORMAL = $00
!LINK_MOVEMENT_SPEED_SETTING_STAIRS = $02
!LINK_MOVEMENT_SPEED_SETTING_DASHING = $10

base $90
oam_main_buffer_current_position:

base $92
oam_small_buffer_current_position:

base $E8
bg2_vertical_scroll_register:

base $F6
controller_1_input_msb:			;AXLR0000

base $010C
temp_storage_global_module_index:

base $0CAA
sprite_vulnerability:
;Bit 7: prevents it from pausing

;sprite positioning data
base $0D00          ;[one byte for each of 0x10 sprites]
sprite_lsb_y:
base $0D10          ;[one byte for each of 0x10 sprites]
sprite_lsb_x:
base $0D20          ;[one byte for each of 0x10 sprites]
sprite_msb_y:
base $0D30          ;[one byte for each of 0x10 sprites]
sprite_msb_x:

base $0DC0          ;[one byte for each of 0x10 sprites]
sprite_pose_index:  ;used internally by the sprite, stores pose number

base $0DE0          ;[one byte for each of 0x10 sprites]
sprite_body_facing:
!SPRITE_BODY_FACING_DIRECTION_UP = $00
!SPRITE_BODY_FACING_DIRECTION_DOWN = $01
!SPRITE_BODY_FACING_DIRECTION_LEFT = $02
!SPRITE_BODY_FACING_DIRECTION_RIGHT = $03

base $0DD0          ;[one byte for each of 0x10 sprites]
sprite_state:
!SPRITE_STATE_DEAD = $00
!SPRITE_STATE_FALLING_INTO_HOLE = $01
!SPRITE_STATE_GOING_POOF = $02
!SPRITE_STATE_FALLING_INTO_PIT = $05
!SPRITE_STATE_SPAWNING = $08
!SPRITE_STATE_ACTIVE = $09
!SPRITE_STATE_CARRIED_BY_LINK = $0A
!SPRITE_STATE_FROZEN = $0B

base $0E40          ;[one byte for each of 0x10 sprites]
sprite_tile_properties:
!SPRITE_TILE_PROPERTIES_TILE_NUMBER_MASK = $1F		;Bits 0-4: number of tiles in the sprite

base $0E60          ;[one byte for each of 0x10 sprites]
sprite_shadow_properties:
!SPRITE_SHADOW_PROPERTIES_SMALL_SHADOW_MASK = $20		;Bit 5: If set, the shadow is a small 8x8 shadow

base $0EB0          ;[one byte for each of 0x10 sprites]
sprite_head_facing:
!SPRITE_HEAD_FACING_DIRECTION_UP = $00
!SPRITE_HEAD_FACING_DIRECTION_DOWN = $01
!SPRITE_HEAD_FACING_DIRECTION_LEFT = $02
!SPRITE_HEAD_FACING_DIRECTION_RIGHT = $03

base $0F00          ;[one byte for each of 0x10 sprites]
sprite_pause:
!SPRITE_PAUSE_OFF = $00
!SPRITE_PAUSE_ON = $01   ;any nonzero value

base $0F10          ;[one byte for each of 0x10 sprites]
sprite_mash_interaction_delay_timer:

base $0FC1
global_spotlight_effect:    ;used during the Book of Mudora sequence to hide other sprites
!GLOBAL_SPOTLIGHT_OFF = $00
!GLOBAL_SPOTLIGHT_ON = $01

base $1CD8
dialogue_subcontroller:

base $1FC0
text_message_index_lsb:
base $1FC1
text_message_index_msb:

base $7FFA1C          ;[one byte for each of 0x10 sprites]
sprite_lift_height:   ;for instance, when you are lifting something, goes progressively from 0-3
!SPRITE_LIFT_HEIGHT_MAX = $03
